Rozwiązania do zajęć 2
WebAce-Group/java101-edycja1 pull request #109
Opened 2023-03-10 20:23 UTC by Asttraios

2023-03-11 17:58 UTC, xEdziu requested changes
Zadanie 6 i 7 niedokończone

2023-03-11 18:19 UTC, xEdziu requested changes
Zadanie 6 i 7 nie dokończone

2023-03-11 22:59 UTC, Asttraios commented
Poprawione 6 i 7

2023-03-12 00:08 UTC, xEdziu requested changes

2023-03-12 00:08 UTC, xEdziu commented on w2/zadania/Asttraios/Zadanie7.java
> +        System.out.println("Srednia= "+ (suma/licznik));
Średnia może wyjść zmiennoprzecinkowa, nie tylko jako `int`. Spróbuj zmienić odpowiednie wartości w linijce 8

2023-03-12 13:27 UTC, Asttraios commented on w2/zadania/Asttraios/Zadanie7.java
> +        System.out.println("Srednia= "+ (suma/licznik));
Nie do końca rozumiem. Program działa poprawnie i wyświetla wyniki zmiennoprzecinkowe. Mam zmienić "suma" i "licznik" na double?

2023-03-12 18:20 UTC, xEdziu commented on w2/zadania/Asttraios/Zadanie7.java
> +        System.out.println("Srednia= "+ (suma/licznik));
![image](https://user-images.githubusercontent.com/50357817/224564390-17a4c1c1-9c96-4f8b-a0c8-f7cf327ff4da.png)

Chodzi o wynik - dostajemy w nim wartość całkowitą

2023-03-12 18:21 UTC, xEdziu approved these changes
Dokładnie, o to chodziło

2023-03-12 18:21 UTC, merged