Rozwiązanie zadań 2
WebAce-Group/java101-edycja1 pull request #114
Opened 2023-03-11 18:13 UTC by MiloszWS

2023-03-11 18:33 UTC, xEdziu requested changes

2023-03-11 18:33 UTC, xEdziu commented on w2/Zadania/MiloszWS/Zadanie3.java
> +            System.out.println("Trojkąt jest równoramienny.");
![image](https://user-images.githubusercontent.com/50357817/224505602-f8f3b52e-9357-4dfd-b59a-8e515fc5531c.png)
Cżyżby na 100% jest równoramienny?

2023-03-11 18:33 UTC, xEdziu commented on w2/Zadania/MiloszWS/Zadanie7.java
> +        srednia=suma/licznik;
Średnia powinna móc mieć wartości zmiennoprzecinkowe

2023-03-12 20:21 UTC, MiloszWS commented on w2/Zadania/MiloszWS/Zadanie7.java
> +        srednia=suma/licznik;
> Średnia powinna móc mieć wartości zmiennoprzecinkowe

Otóż oba błędy zostały poprawione jak mniemam.

2023-03-13 12:33 UTC, xEdziu approved these changes

2023-03-13 12:33 UTC, merged