Rozwiazanie zadan z wykladu w2
WebAce-Group/java101-edycja1 pull request #119
Opened 2023-03-12 15:11 UTC by szxxlc

2023-03-13 12:37 UTC, xEdziu requested changes

2023-03-13 12:37 UTC, xEdziu commented on w2/Zadania/szxxlc/Zadanie7.java
> +        System.out.println("Srednia podanych liczb: " + suma/ilosc);
średnia nie jest zmienno przecinkowa

2023-03-13 12:38 UTC, szxxlc commented on w2/Zadania/szxxlc/Zadanie7.java
> +        System.out.println("Srednia podanych liczb: " + suma/ilosc);
aha

2023-03-27 22:31 UTC, xEdziu approved these changes

2023-03-27 22:32 UTC, xEdziu approved these changes

2023-03-27 22:32 UTC, merged