Zadania w3
WebAce-Group/java101-edycja1 pull request #172
Opened 2023-03-27 13:50 UTC by Ziolo03

2023-03-27 21:29 UTC, Kubis10 commented on w3/zadania/Ziolo03/Zadanie13.java
> +            case 2,1,0:
Powineneś w ten sposób cases napisać
            case 2:
            case 1:
            case 0:

2023-03-27 21:34 UTC, Kubis10 requested changes

2023-03-27 21:34 UTC, Kubis10 commented on w3/zadania/Ziolo03/Zadanie13.java
Więc to do poprawy

2023-05-11 09:00 UTC, xEdziu approved these changes

2023-05-11 09:01 UTC, merged