Zadania, wykład 2
WebAce-Group/java101-edycja1 pull request #83
Opened 2023-03-01 23:22 UTC by MiloszWS

Trochę bałagan, jeszcze ogarnianie gita jest...

2023-03-09 21:17 UTC, xEdziu commented
![image](https://user-images.githubusercontent.com/50357817/224161841-33dc1a04-3aff-434d-bfe9-7c7527ce565d.png)

jak

2023-03-09 22:00 UTC, xEdziu commented
Zgłoś się do mnie na discordzie, spróbuję pomóc z ogarnięciem tego

2023-03-09 22:19 UTC, xEdziu requested changes
Zgłoś się na ds - pomogę ogarnąć <3

2023-03-10 08:44 UTC, MiloszWS commented
> Zgłoś się na ds - pomogę ogarnąć <3

Dzisiaj po 22 pasuje? (Prace muszę skończyć) Czy jutro około 12 lepiej?

2023-03-10 08:47 UTC, xEdziu commented
Już lepiej jutro niż dziś, dziś jestem wyjęty niestety :(

2023-03-11 08:33 UTC, MiloszWS commented
> Już lepiej jutro niż dziś, dziś jestem wyjęty niestety :(

To odezwę się dzisiaj wieczorem jednak w takim razie.

2023-03-11 18:03 UTC, closed without merging