Rozwiązania zadań z zajęć 2
WebAce-Group/java101-edycja1 pull request #84
Opened 2023-03-02 14:15 UTC by Feredi123

2023-03-09 22:03 UTC, xEdziu requested changes

2023-03-09 22:03 UTC, xEdziu commented on w2/zadania/Feredi123/Zadanie3.java
> +            System.out.println("trójkąt równoramienny");
niby tak, jednak nie do końca
![image](https://user-images.githubusercontent.com/50357817/224170338-4e6885ea-5961-44de-9dd7-92357ff6c830.png)

2023-03-10 18:05 UTC, Feredi123 commented on w2/zadania/Feredi123/Zadanie3.java
> +            System.out.println("trójkąt równoramienny");
już poprawiłem błąd, w 15 lini zamiast if powinno być else if
![obraz](https://user-images.githubusercontent.com/125486210/224390438-93181e2a-f2d4-4c3d-976a-b2e2ab8ba853.png)

2023-03-10 18:07 UTC, xEdziu approved these changes

2023-03-10 18:08 UTC, merged