Rozwiązania zadań z wykładu 2
WebAce-Group/java101-edycja1 pull request #85
Opened 2023-03-02 17:36 UTC by mmarkowski321

2023-03-09 22:04 UTC, xEdziu requested changes
![image](https://user-images.githubusercontent.com/50357817/224170630-ed7b2f07-a939-457e-9528-5a734bf8d10d.png)

Popraw proszę folder w w2

2023-03-10 11:40 UTC, xEdziu requested changes

2023-03-10 11:40 UTC, xEdziu commented on w2/zadania/mmarkowski321/zadanie7.java
> +        System.out.println(suma/liczbaProb);
Średnia może wyjść zmiennoprzecinkowa

2023-03-13 17:17 UTC, mmarkowski321 commented on w2/zadania/mmarkowski321/zadanie7.java
> +        System.out.println(suma/liczbaProb);
Faktycznie, już poprawione

2023-04-03 16:53 UTC, closed without merging